# Generated by Django 5.2.17 on 2026-08-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_tv_advance_unit_event_tv_advance_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('AUDIENCIA', 'Audiência'), ('REUNIAO', 'Reunião'), ('PRAZO', 'Prazo'), ('CONTRATO', 'Contrato'), ('OITIVA', 'Oitiva')], db_index=True, max_length=30, verbose_name='Tipo'),
        ),
    ]
